sudo: false
language: node_js
dist: trusty
addons:
  apt:
    packages:
      - libnss3
node_js:
  - '9'
  - '8'
cache:
  directories:
    - node_modules
before_script:
  - npm prune
after_success:
  - npm run report
