sudo: false
language: node_js
node_js:
  - '9'
  - '8'
cache:
  directories:
    - node_modules
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm prune
after_success:
  - npm run report
